### ISSUE TITLE
Saitek FIP Flight Instrument Panel

### ISSUE THREAD

**Issue by webknjaz** [daibach142/SaitekSwitch#3]
Hi Dave,

I've been searching for ways to support $sbj under Linux but haven't found anything not requiring some obscure Windows-only Direct Output dll provided by Logitech. My understanding is that it's essentially a screen that is able to show bitmaps sent over USB and the computer side should probably be able to get button presses too.

So since saw you successfully implementing software that works with some other Saitek panels, I wanted to ask if you ever looked into this one too? Unfortunately, I don't really have experience working with hardware so it's hard for me to even find where to start looking into the communication protocol for the device. Would you have any pointers for me?

**Comment by daibach142** [comment]
Hi @webknjaz 

I would need to find the protocol used by the FIP, and would require some testing done by someone with the device.
For the switch panel, I wrote a panel simulator in C (_before I converted to using mainly Rust!)_) and   @BruceMaggs helped debug with his panel.

Watch this space.
Regard
Dave

**Comment by webknjaz** [comment]
> I would need to find the protocol used by the FIP, and would require some testing done by someone with the device.

That's what I can't figure out — there doesn't seem to be any public information regarding this. And I don't know if it's possible to somehow capture the interaction between the closed source windows library and the device. I don't have Windows normally but could probably run that thing in a VM, if that'd make it possible to intercept the communication...
I have the device and could look into it if there's any pointers on how to do that.

**Comment by BruceMaggs** [comment]
Since it's a USB device, you might be able to capture the packets sent between Windows and the device using Wireshark.  There's some information here:

https://wiki.wireshark.org/CaptureSetup/USB

Alternatively, there are USB packet capture devices that you can put in-line between the Windows machine and the USB device, such as this:

https://lab401.com/products/bugblat-minisniffer-v2

(But I don't have any personal experience with the minisniffer.)

Most likely the data won't be encryptyed.  Reverse engineering the protocol may be quite difficult, however, even if you can see the underlying data exchange.

**Comment by daibach142** [comment]
Sorry guys - crossed wires here (direct response to @BruceMaggs )

**Comment by webknjaz** [comment]
Thanks for the pointers! Now I need to figure out how to trigger the data exchange: I'd rather not run a heavy app like MSFS in a VM if there's a lighter alternative...

**Comment by daibach142** [comment]
Can't find the info, and don't have the device, so lets close this as not part of this project

**Comment by daibach142** [comment]
closed
